name: text_recognition
description: A new Flutter project.
publish_to: 'none'


environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_mlkit_text_recognition: ^0.11.0
  camera: ^0.10.5+9
  permission_handler: ^11.0.1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  share_plus: ^7.2.1
  google_mlkit_translation: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  #flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
